config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :styles
  resources :beers
  resources :styles
  resources :breweries
  resources :opinions
  resources :users
  get 'welcome' => 'breweries#welcome'

  root "breweries#index"

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  has_many :breweries
  has_many :opinions
  has_many :breweries, through: :styles
  belongs_to :style
  belongs_to :brewery

    def average_rating
      if opinions.count > 0
        opinions.pluck(:rating).sum / opinions.count
      else
        0
      end
    end

end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]

  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.all
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
    @opinion = Opinion.new
    @rating = @beer.average_rating
  end

  # GET /beers/new
  def new
    @brewery = Brewery.where(brewery_id: params[:id])
    @beer = Beer.new
    # @style = Style.find_or_create_by(style_params)
    # @brewery = Brewery.find_or_create_by(brewery_params)
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to @beer, notice: 'Beer was successfully created.' }
        format.json { render :show, status: :created, location: @beer }
      else
        format.html { render :new }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer }
      else
        format.html { render :edit }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url, notice: 'Beer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_params
      params.require(:beer).permit(:name, :brewery_id, :style_id)
    end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% @beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :brewery_id %><br>
    <%= f.text_field :brewery_id %>
  </div>
  <div class="field">
    <%= f.label :style_id %><br>
    <%= f.text_field :style_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beers/edit.html.erb
<h1>Editing Beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Beers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Style</th>
      <th>Brewery</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beers.each do |beer| %>
      <tr>
        <td><%= link_to beer.name, beer %></td>
        <td><%= link_to beer.style.name, beer.style %></td>
        <td><%= link_to beer.brewery.name, beer.brewery%></td>
        <td><%= link_to 'Show', beer %></td>
        <td><%= link_to 'Edit', edit_beer_path(beer) %></td>
        <td><%= link_to 'Destroy', beer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beer', new_beer_path %>

app/views/beers/new.html.erb
<h1>New Beer</h1>

<%= render 'form' %>

<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @beer.name %>
</p>
<p>
  <strong>Rating</strong>
  <%= @rating %>
</p>

<p>
  <strong>Style:</strong>
  <%= @beer.style.name %>
</p>

<p>
  <strong>Brewery:</strong>
  <%= @beer.brewery.name %>
</p>
      <%= form_for(@opinion) do |f| %>
        <% if @opinion.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@opinion.errors.count, "error") %> prohibited this brewery from being saved:</h2>

            <ul>
            <% @opinion.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= f.label :rating %><br>
          <%= f.text_field :rating %>
        </div>
        <div class="field">
          <%= f.label :review %><br>
          <%= f.text_field :review %>
        </div>
        <div class="field">
          <%= f.hidden_field :like, value: 1 %>
        </div>
         <div class="field">
          <%= f.hidden_field :user_id, value: current_user.id %>
        </div>
        <div class="field">
          <%= f.hidden_field :brewery_id, value: @beer.brewery.id %>
        </div>
        <div class="field">
          <%= f.hidden_field :beer_id, value: @beer.id %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
      <% end %>

<%= link_to 'Edit', edit_beer_path(@beer) %> |
<%= link_to 'Back', beers_path %>